name: dB Meter
options:
  bundleIdPrefix: com.dantanner
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"

targets:
  dB Meter:
    type: application
    platform: macOS
    sources:
      - path: dB Meter
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dantanner.dB-Meter
        INFOPLIST_FILE: "dB Meter/Info.plist"
        CODE_SIGN_ENTITLEMENTS: "dB Meter/dBMeter.entitlements"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: false
        MACOSX_DEPLOYMENT_TARGET: "14.0"
